import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <p>Header</p>
          <Link href='/login'>Login</Link>
          <Link href='/categories/test'>Test</Link>
        </div>
        {children}
        <div>
          <p>Footer</p>
        </div>
      </body>
    </html>
  );
}
